default: &default
  title: wGaoKao
  host: localhost:3000

  mailer:
    # For localhost postfix
    smtp_settings:
      address: smtp.gmail.com
      port: 587
      enable_starttls_auto: true
      domain: gmail.com
      # user_name: "****@gmail.com"
      # password: "*****"  # longin your gmail
      authentication: plain
    default_options:
      from: no-reply@wgaokao.org
    default_url_options:
      host: localhost:3000

  redis:
    host: 127.0.0.1
    port: 6379
    db: 0

  elasticsearch:
    host: localhost:9200

development:
  <<: *default
  admin_emails:
    - 765732980@qq.com

test:
  <<: *default
  admin_emails:
    - 765732980@qq.com

production:
  <<: *default

  admin_emails:
    - 765732980@qq.com
