default: &default
  title: wGaoKao
  host: localhost:3000

  mailer:
    # For localhost postfix
    smtp_settings:
      address: smtp.mailgun.org
      port: 25
      enable_starttls_auto: true
      # user_name: ******.mailgun.org
      # password: 2****j29
      authentication: plain
    default_options:
      from: no-reply@wgaokao.org
    default_url_options:
      host: localhost:3000

  redis:
    host: 127.0.0.1
    port: 6379
    db: 0

  elasticsearch:
    host: localhost:9200

development:
  <<: *default
  admin_emails:
    - 765732980@qq.com

test:
  <<: *default
  admin_emails:
    - 765732980@qq.com

production:
  <<: *default

  admin_emails:
    - 765732980@qq.com
